use_frameworks!

platform :ios, '8.0'

target 'PYJsonViewManager_Example' do
  pod 'PYJsonViewManager', :path => '../'

  target 'PYJsonViewManager_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
